// 1. Write a JavaScript program to compare two objects to determine if the first one contains equivalent property values to the second one. Go to the editor



// 76. Write a JavaScript program to execute a provided function once for each array element, starting from the array's last element.Go to the editor

// Click me to see the solution

// 77. Write a JavaScript program to iterate over all own properties of an object, running a callback for each one. Go to the editor

// Click me to see the solution

// 78. Write a JavaScript program to invert the key-value pairs of an object, without mutating it. The corresponding inverted value of each inverted key is an array of keys responsible for generating the inverted value. If a function is supplied, it is applied to each inverted key. Go to the editor

// Click me to see the solution

// 79. Write a JavaScript program to take any number of iterable objects or objects with a length property and returns the longest one. Go to the editor

// Click me to see the solution

// 80. Write a JavaScript program to implement the Luhn Algorithm used to validate a variety of identification numbers, such as credit card numbers, IMEI numbers, National Provider Identifier numbers etc. Go to the editor

// Click me to see the solution

// 81. Write a JavaScript program to create an object with keys generated by running the provided function for each key and the same values as the provided object. Go to the editor

// Click me to see the solution

// 82. Write a JavaScript program to map the values of an array to an object using a function, where the key-value pairs consist of the original value as the key and the mapped value. Go to the editor

// Click me to see the solution

// 83. Write a JavaScript program to create a new string with the results of calling a provided function on every character in the calling string. Go to the editor

// Click me to see the solution

// 84. Write a JavaScript program to create an object with the same keys as the provided object and values generated by running the provided function for each value. Go to the editor

// Click me to see the solution

// 85. Write a JavaScript program to replace all but the last number of characters with the specified mask character. Go to the editor

// Click me to see the solution

// 86. Write a JavaScript program to get the maximum value of an array, after mapping each element to a value using the provided function. Go to the editor

// Click me to see the solution

// 87. Write a JavaScript program to get the n maximum elements from the provided array. If n is greater than or equal to the provided array's length, then return the original array(sorted in descending order). Go to the editor

// Click me to see the solution

// 88. Write a JavaScript program to get the median of an array of numbers. Go to the editor

// Click me to see the solution

// 89. Write a JavaScript program to negates a predicate function.Go to the editor

// Click me to see the solution

// 90. Write a JavaScript program to nest a given flat array of objects linked to one another recursively. Go to the editor

// Click me to see the solution

// 91. Write a JavaScript program that will return true if the provided predicate function returns false for all elements in a collection, false otherwise. Go to the editor

// Click me to see the solution

// 92. Write a JavaScript program to create a function that gets the argument at index n. If n is negative, the nth argument from the end is returned. Go to the editor

// Click me to see the solution

// 93. Write a JavaScript program to remove an event listener from an element. Go to the editor

// Click me to see the solution

// 94. Write a JavaScript program to move the specified amount of elements to the end of the array. Go to the editor

// Click me to see the solution

// 95. Write a JavaScript program to add an event listener to an element with the ability to use event delegation. Go to the editor

// Click me to see the solution

// 96. Write a JavaScript program to pick the key-value pairs corresponding to the given keys from an object. Go to the editor

// Click me to see the solution

// 97. Write a JavaScript program to create an object composed of the properties the given function returns truthy for. The function is invoked with two arguments: (value, key). Go to the editor

// Click me to see the solution

// 98. Write a JavaScript program to filter an array of objects based on a condition while also filtering out unspecified keys. Go to the editor

// Click me to see the solution

// 99. Write a JavaScript program to hash a given input string into a whole number. Go to the editor

// Click me to see the solution

// 100. Write a JavaScript program to create an array of elements, grouped based on the position in the original arrays and using function as the last value to specify how grouped values should be combined. Go to the editor

// Click me to see the solution

// 101. Write a JavaScript program to return the object associating the properties to the values of a given array of valid property identifiers and an array of values. Go to the editor

// Click me to see the solution

// 102. Write a JavaScript program to create an array of elements, grouped based on the position in the original arrays. Go to the editor

// Click me to see the solution

// 103. Write a JavaScript program to convert a given string into an array of words. Go to the editor

// Click me to see the solution

// 104. Write a JavaScript program to test a value, x, against a predicate function. If true, return fn(x). Else, return x. Go to the editor

// Click me to see the solution

// 105. Write a JavaScript program that return true if the given value is a number, false otherwise. Go to the editor

// Click me to see the solution

// 106. Write a JavaScript program to create an array of elements, ungrouping the elements in an array produced by zip and applying the provided function. Go to the editor

// Click me to see the solution

// 107. Write a JavaScript program to get all unique values (form the right side of the array) of an array, based on a provided comparator function.Go to the editor

// Click me to see the solution

// 108. Write a JavaScript program to get all unique values of an array, based on a provided comparator function. Go to the editor

// Click me to see the solution

// 109. Write a JavaScript program to get the nth element of a given array. Go to the editor

// Click me to see the solution

// 110. Write a JavaScript program to get every element that exists in any of the two arrays once. Go to the editor

// Click me to see the solution

// 111. Write a JavaScript program to build an array, using an iterator function and an initial seed value. Go to the editor

// Click me to see the solution

// 112. Write a JavaScript program to unflatten an object with the paths for keys. Go to the editor

// Click me to see the solution

// 113. Write a JavaScript program to unescape escaped HTML characters. Go to the editor

// Click me to see the solution

// 114. Write a JavaScript program to uncurry a function up to depth n. Go to the editor

// Click me to see the solution

// 115. Write a JavaScript program to create a function that accepts up to one argument, ignoring any additional arguments.Go to the editor

// Click me to see the solution

// 116. Write a JavaScript program to check if the predicate (second argument) is truthy on all elements of a collection (first argument). Go to the editor

// Click me to see the solution

// 117. Write a JavaScript program to truncate a string up to a specified length. Go to the editor

// Click me to see the solution

// 118. Write a JavaScript program to apply a function against an accumulator and each key in the object (from left to right). Go to the editor

// Click me to see the solution

// 119. Write a JavaScript program to create tomorrow's date in a string representation. Go to the editor

// Click me to see the solution

// 120. Write a JavaScript program to convert a string to snake case. Go to the editor

// Click me to see the solution

// 121. Write a JavaScript program to convert a value to a safe integer. Go to the editor

// Click me to see the solution

// 122. Write a JavaScript program to add an ordinal suffix to a number. Go to the editor

// Click me to see the solution

// 123. Write a JavaScript program to convert a string to kebab case. Go to the editor

// Click me to see the solution

// 124. Write a JavaScript program to reduce a given Array-like into a value hash (keyed data store). Go to the editor

// Click me to see the solution

// 125. Write a JavaScript program to convert a float-point arithmetic to the Decimal mark form and It will make a comma separated string from a number. Go to the editor

// Click me to see the solution

// 126. Write a JavaScript program to create a specified currency formatting from a given number. Go to the editor

// Click me to see the solution

// 127. Write a JavaScript program to Iterate over a callback n times. Go to the editor

// Click me to see the solution

// 128. Write a JavaScript program to get removed elements of a given array until the passed function returns true. Go to the editor

// Click me to see the solution

// 129. Write a JavaScript program to get removed elements from the end of a given array until the passed function returns true. Go to the editor

// Click me to see the solution

// 130. Write a JavaScript program to remove n elements from the end of a given array. Go to the editor

// Click me to see the solution

// 131. Write a JavaScript program to get an array with n elements removed from the beginning from a given array Go to the editor

// Click me to see the solution

// 132. Write a JavaScript program to get the symmetric difference between two given arrays, using a provided function as a comparator. Go to the editor

// Click me to see the solution

// 133. Write a JavaScript program to get the symmetric difference between two given arrays, after applying the provided function to each array element of both. Go to the editor

// Click me to see the solution

// 134. Write a JavaScript program to get the symmetric difference between two given arrays. Go to the editor

// Click me to see the solution

// 135. Write a JavaScript program to get the sum of the powers of all the numbers from start to end (both inclusive)